#This is temporary. Please improve
language: go

go:
  - 1.17

script:
  - echo "Testing"
  - go test ./... -v -coverpkg=./...  -coverprofile=coverage.out
  - go tool cover -html=coverage.out -o cover.html